CREATE SCHEMA IF NOT EXISTS staging;


CREATE TABLE IF NOT EXISTS staging.clientes (

    ID_CLIENTE INTEGER,
    CLIENTE VARCHAR(150),
    EMAIL VARCHAR(150),
    ESTADO CHAR(2),
    DATA_CADASTRO DATE,
    STATUS VARCHAR(20)
);


CREATE TABLE IF NOT EXISTS staging.categoria(
    ID_CATEGORIA INTEGER,
    CATEGORIA VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS staging.faturamento (
    NF INTEGER,
    ID_PEDIDO INTEGER,
    DATA_FATURAMENTO DATE,
    FORMA_PAGAMENTO VARCHAR(30),
    VALOR_FATURAMENTO NUMERIC(15,2),
    STATUS_FATURAMENTO VARCHAR(30)

);


CREATE TABLE IF NOT EXISTS staging.itens_pedidos (
    ID_ITEM INTEGER,
    ID_PEDIDO INTEGER,
    ID_PRODUTO INTEGER,
    QUANTIDADE INTEGER,
    PRECO_UNITARIO NUMERIC(15,2),
    DESCONTO_PERC NUMERIC (5,4),
    VALOR_BRUTO NUMERIC(15,2),
    VALOR_DESCONTO NUMERIC(15,2),
    VALOR_LIQUIDO NUMERIC(15,2),
    CUSTO_UNITARIO NUMERIC(15,2)
);


CREATE TABLE IF NOT EXISTS staging.pedido (
    ID_PEDIDO INTEGER,
    ID_CLIENTE INTEGER,
    ID_VENDEDOR INTEGER,
    DATA_PEDIDO DATE,
    STATUS_PEDIDO VARCHAR(20),
    QTD_ITEM INTEGER,
    VALOR_BRUTO NUMERIC(15,2),
    VALOR_DESCONTO NUMERIC(15,2),
    VALOR_LIQUIDO NUMERIC(15,2)

);

CREATE TABLE IF NOT EXISTS staging.produto(
    ID_PRODUTO INTEGER,
    ID_CATEGORIA INTEGER,
    PRODUTO VARCHAR(100),
    CUSTO_UNITARIO NUMERIC(15,2),
    PRECO_TABELA NUMERIC(15,2),
    STATUS VARCHAR(20)
);


CREATE TABLE IF NOT EXISTS staging.vendedor(
    ID_VENDEDOR INTEGER,
    NOME VARCHAR(150),
    ESTADO CHAR(2),
    CANAL_VENDA VARCHAR(50)
);